In [56]:
import sqlite3
import pandas as pd

In [57]:
conn = sqlite3.connect("mykpopidolsdatabase.db")
cursor = conn.cursor()

In [58]:
cursor.execute("DROP TABLE IF EXISTS kpopagency")
cursor.execute("DROP TABLE IF EXISTS kpopidolgroup")
cursor.execute("DROP TABLE IF EXISTS kpopgroupmembers")
conn.commit()

In [59]:
cursor.execute("""
CREATE TABLE IF NOT EXISTS kpopagency(id
    INTEGER PRIMARY KEY AUTOINCREMENT,
    agency TEXT,
    location TEXT,
    date_established DATE,
    number_of_kpop_groups_debuted INT,
    ownername TEXT
)
""")
conn.commit()

In [60]:
cursor.execute("""
CREATE TABLE IF NOT EXISTS kpopidolgroup(id
    INTEGER PRIMARY KEY AUTOINCREMENT,
    kpop_group_name TEXT,
    type TEXT,
    debut_date DATE,
    number_of_members INT,
    agencyID INT
)
""")
conn.commit()

In [61]:
cursor.execute("""
CREATE TABLE IF NOT EXISTS kpopgroupmembers(idol_member_id
    INTEGER PRIMARY KEY AUTOINCREMENT,
    stage_name TEXT,
    real_name TEXT,
    gender TEXT,
    birthday DATE,
    position TEXT,
    zodiac TEXT,
    personality_type TEXT,
    kpopgroup_id INTEGER,
    agency_id INTEGER
)
""")
conn.commit()

In [62]:
cursor.execute("INSERT INTO kpopagency(agency, location, date_established, number_of_kpop_groups_debuted, ownername)VALUES(?, ?, ?, ?, ?)",("SM Entertainment", "Seoul, South Korea", "1995-02-14", 15, "Lee Soo-man"))
cursor.execute("INSERT INTO kpopagency(agency, location, date_established, number_of_kpop_groups_debuted, ownername)VALUES(?, ?, ?, ?, ?)",("YG Entertainment", "Seoul, South Korea", "1996-02-24", 10, "Yang Hyun-suk"))
cursor.execute("INSERT INTO kpopagency(agency, location, date_established, number_of_kpop_groups_debuted, ownername)VALUES(?, ?, ?, ?, ?)",("JYP Entertainment", "Seoul, South Korea", "1997-04-25", 10, "Park Jin-young"))
cursor.execute("INSERT INTO kpopagency(agency, location, date_established, number_of_kpop_groups_debuted, ownername)VALUES(?, ?, ?, ?, ?)",("HYBE Entertainment", "Seoul, South Korea", "2005-02-01", 8, "Bang Si-hyuk"))
cursor.execute("INSERT INTO kpopagency(agency, location, date_established, number_of_kpop_groups_debuted, ownername)VALUES(?, ?, ?, ?, ?)",("Starship Entertainment", "Seoul, South Korea", "2008-01-28", 6, "Kim Shi-dae"))
cursor.execute("INSERT INTO kpopagency(agency, location, date_established, number_of_kpop_groups_debuted, ownername)VALUES(?, ?, ?, ?, ?)",("Cube Entertainment", "Seoul, South Korea", "2006-08-29", 7, "Hong Seung-sung"))
cursor.execute("INSERT INTO kpopagency(agency, location, date_established, number_of_kpop_groups_debuted, ownername)VALUES(?, ?, ?, ?, ?)",("Pledis Entertainment", "Seoul, South Korea", "2007-01-01", 5, "Han Sung-soo"))
cursor.execute("INSERT INTO kpopagency(agency, location, date_established, number_of_kpop_groups_debuted, ownername)VALUES(?, ?, ?, ?, ?)",("RBW", "Seoul, South Korea", "2010-03-05", 4, "Kim Jin-woo"))
cursor.execute("INSERT INTO kpopagency(agency, location, date_established, number_of_kpop_groups_debuted, ownername)VALUES(?, ?, ?, ?, ?)",("Woollim Entertainment", "Seoul, South Korea", "2010-06-09", 6, "Lee Jung-yeop"))
cursor.execute("INSERT INTO kpopagency(agency, location, date_established, number_of_kpop_groups_debuted, ownername)VALUES(?, ?, ?, ?, ?)",("FNC Entertainment", "Seoul, South Korea", "2006-12-14", 8, "Han Seong-ho"))

In [63]:
df_agencies = pd.read_sql_query("SELECT * FROM kpopagency", conn)
df_agencies

,id,agency,location,date_established,number_of_kpop_groups_debuted,ownername
0,1,SM Entertainment,"Seoul, South Korea",1995-02-14,15,Lee Soo-man
1,2,YG Entertainment,"Seoul, South Korea",1996-02-24,10,Yang Hyun-suk
2,3,JYP Entertainment,"Seoul, South Korea",1997-04-25,10,Park Jin-young
3,4,HYBE Entertainment,"Seoul, South Korea",2005-02-01,8,Bang Si-hyuk
4,5,Starship Entertainment,"Seoul, South Korea",2008-01-28,6,Kim Shi-dae
5,6,Cube Entertainment,"Seoul, South Korea",2006-08-29,7,Hong Seung-sung
6,7,Pledis Entertainment,"Seoul, South Korea",2007-01-01,5,Han Sung-soo
7,8,RBW,"Seoul, South Korea",2010-03-05,4,Kim Jin-woo
8,9,Woollim Entertainment,"Seoul, South Korea",2010-06-09,6,Lee Jung-yeop
9,10,FNC Entertainment,"Seoul, South Korea",2006-12-14,8,Han Seong-ho

In [64]:
cursor.execute("INSERT INTO kpopidolgroup(kpop_group_name, type, debut_date, number_of_members, agencyID)VALUES(?, ?, ?, ?, ?)",("aespa", "Metaverse concept-Girl group", "2020-11-17", 4, 1))
cursor.execute("INSERT INTO kpopidolgroup(kpop_group_name, type, debut_date, number_of_members, agencyID)VALUES(?, ?, ?, ?, ?)",("BLACKPINK", "Girl crush-Girl group", "2016-08-08", 4, 2))
cursor.execute("INSERT INTO kpopidolgroup(kpop_group_name, type, debut_date, number_of_members, agencyID)VALUES(?, ?, ?, ?, ?)",("TWICE", "Bright pop-Girl group", "2015-10-20", 9, 3))
cursor.execute("INSERT INTO kpopidolgroup(kpop_group_name, type, debut_date, number_of_members, agencyID)VALUES(?, ?, ?, ?, ?)",("TXT", "Youth growth-Boy group", "2019-03-04", 5, 4))
cursor.execute("INSERT INTO kpopidolgroup(kpop_group_name, type, debut_date, number_of_members, agencyID)VALUES(?, ?, ?, ?, ?)",("IVE", "Luxury teen-Girl group", "2021-12-01", 6, 5))
cursor.execute("INSERT INTO kpopidolgroup(kpop_group_name, type, debut_date, number_of_members, agencyID)VALUES(?, ?, ?, ?, ?)",("(G)I-DLE", "Self producing experimental-Girl group", "2018-05-21", 5, 6))
cursor.execute("INSERT INTO kpopidolgroup(kpop_group_name, type, debut_date, number_of_members, agencyID)VALUES(?, ?, ?, ?, ?)",("SEVENTEEN", "Self-producing performance-Boy group", "2015-05-26", 13, 7))
cursor.execute("INSERT INTO kpopidolgroup(kpop_group_name, type, debut_date, number_of_members, agencyID)VALUES(?, ?, ?, ?, ?)",("MAMAMOO", "Vocal powerhouese-Girl group", "2014-06-18", 4, 8))
cursor.execute("INSERT INTO kpopidolgroup(kpop_group_name, type, debut_date, number_of_members, agencyID)VALUES(?, ?, ?, ?, ?)",("INFINITE", "Synchronization-Boy group", "2010-06-09", 6, 9))
cursor.execute("INSERT INTO kpopidolgroup(kpop_group_name, type, debut_date, number_of_members, agencyID)VALUES(?, ?, ?, ?, ?)",("SF9", "Performance-focused-Boy group", "2016-10-05", 6, 10))

In [65]:
df_groups = pd.read_sql_query("SELECT * FROM kpopidolgroup", conn)
df_groups

,id,kpop_group_name,type,debut_date,number_of_members,agencyID
0,1,aespa,Metaverse concept-Girl group,2020-11-17,4,1
1,2,BLACKPINK,Girl crush-Girl group,2016-08-08,4,2
2,3,TWICE,Bright pop-Girl group,2015-10-20,9,3
3,4,TXT,Youth growth-Boy group,2019-03-04,5,4
4,5,IVE,Luxury teen-Girl group,2021-12-01,6,5
5,6,(G)I-DLE,Self producing experimental-Girl group,2018-05-21,5,6
6,7,SEVENTEEN,Self-producing performance-Boy group,2015-05-26,13,7
7,8,MAMAMOO,Vocal powerhouese-Girl group,2014-06-18,4,8
8,9,INFINITE,Synchronization-Boy group,2010-06-09,6,9
9,10,SF9,Performance-focused-Boy group,2016-10-05,6,10

In [66]:
cursor.execute("INSERT INTO kpopgroupmembers(stage_name, real_name, gender, birthday, position, zodiac, personality_type, kpopgroup_id, agency_id)VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?)",("Karina", "Yoo Ji-min", "Female", "2000-04-11", "Leader", "Aries", "ENFP", 1, 1))
cursor.execute("INSERT INTO kpopgroupmembers(stage_name, real_name, gender, birthday, position, zodiac, personality_type, kpopgroup_id, agency_id)VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?)",("Jisoo", "Kim Ji-soo", "Female", "1995-01-03", "Visual", "Capricorn", "INFJ", 2, 2))
cursor.execute("INSERT INTO kpopgroupmembers(stage_name, real_name, gender, birthday, position, zodiac, personality_type, kpopgroup_id, agency_id)VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?)",("Nayeon", "Im Nayeon", "Female", "1995-09-22", "Lead Vocalist", "Virgo", "ESFJ", 3, 3))
cursor.execute("INSERT INTO kpopgroupmembers(stage_name, real_name, gender, birthday, position, zodiac, personality_type, kpopgroup_id, agency_id)VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?)",("Beomgyu", "Choi Beomgyu", "Male", "2001-03-13", "Visual", "Pisces", "INFP", 4, 4))
cursor.execute("INSERT INTO kpopgroupmembers(stage_name, real_name, gender, birthday, position, zodiac, personality_type, kpopgroup_id, agency_id)VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?)",("Wonyoung", "Jang Wonyoung", "Female", "2004-08-31", "Visual", "Virgo", "ESFP", 5, 5))
cursor.execute("INSERT INTO kpopgroupmembers(stage_name, real_name, gender, birthday, position, zodiac, personality_type, kpopgroup_id, agency_id)VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?)",("Soyeon", "Jeon Soyeon", "Female", "1998-08-26", "Leader", "Virgo", "INTJ", 6, 6))
cursor.execute("INSERT INTO kpopgroupmembers(stage_name, real_name, gender, birthday, position, zodiac, personality_type, kpopgroup_id, agency_id)VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?)",("S.Coups", "Choi Seungcheol", "Male", "1995-08-08", "Leader", "Leo", "ISTJ", 7, 7))
cursor.execute("INSERT INTO kpopgroupmembers(stage_name, real_name, gender, birthday, position, zodiac, personality_type, kpopgroup_id, agency_id)VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?)",("Solar", "Kim Yongsun", "Female", "1991-02-21", "Leader", "Pisces", "ENFJ", 8, 8))
cursor.execute("INSERT INTO kpopgroupmembers(stage_name, real_name, gender, birthday, position, zodiac, personality_type, kpopgroup_id, agency_id)VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?)",("Sungkyu", "Kim Sungkyu", "Male", "1989-04-28", "Leader", "Taurus", "ISTJ", 9, 9))
cursor.execute("INSERT INTO kpopgroupmembers(stage_name, real_name, gender, birthday, position, zodiac, personality_type, kpopgroup_id, agency_id)VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?)",("Taeyang", "Yoo Taeyang", "Male", "1997-02-28", "Main dancer", "Pisces", "ENFJ", 10, 10))

In [67]:
df_members = pd.read_sql_query("SELECT * FROM kpopgroupmembers", conn)
df_members

,idol_member_id,stage_name,real_name,gender,birthday,position,zodiac,personality_type,kpopgroup_id,agency_id
0,1,Karina,Yoo Ji-min,Female,2000-04-11,Leader,Aries,ENFP,1,1
1,2,Jisoo,Kim Ji-soo,Female,1995-01-03,Visual,Capricorn,INFJ,2,2
2,3,Nayeon,Im Nayeon,Female,1995-09-22,Lead Vocalist,Virgo,ESFJ,3,3
3,4,Beomgyu,Choi Beomgyu,Male,2001-03-13,Visual,Pisces,INFP,4,4
4,5,Wonyoung,Jang Wonyoung,Female,2004-08-31,Visual,Virgo,ESFP,5,5
5,6,Soyeon,Jeon Soyeon,Female,1998-08-26,Leader,Virgo,INTJ,6,6
6,7,S.Coups,Choi Seungcheol,Male,1995-08-08,Leader,Leo,ISTJ,7,7
7,8,Solar,Kim Yongsun,Female,1991-02-21,Leader,Pisces,ENFJ,8,8
8,9,Sungkyu,Kim Sungkyu,Male,1989-04-28,Leader,Taurus,ISTJ,9,9
9,10,Taeyang,Yoo Taeyang,Male,1997-02-28,Main dancer,Pisces,ENFJ,10,10

In [68]:
conn.close()